-- Techverse SQL Dump
-- Database: techverse

DROP DATABASE IF EXISTS techverse;
CREATE DATABASE techverse CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE techverse;

-- USERS
CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password_hash VARCHAR(255) DEFAULT NULL,
  role ENUM('user','admin') NOT NULL DEFAULT 'user',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- PRODUCTS
CREATE TABLE products (
  product_id INT AUTO_INCREMENT PRIMARY KEY,
  sku VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(100) NOT NULL,
  brand VARCHAR(100),
  price DECIMAL(10,2) NOT NULL,
  image_url VARCHAR(255) DEFAULT NULL,
  short_desc VARCHAR(512) DEFAULT NULL,
  description TEXT,
  rating FLOAT DEFAULT 0,
  stock INT DEFAULT 10,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX(price),
  INDEX(brand),
  INDEX(category)
) ENGINE=InnoDB;

-- CART ITEMS
CREATE TABLE cart_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  product_id INT NOT NULL,
  quantity INT DEFAULT 1,
  added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (product_id) REFERENCES products(product_id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- WISHLIST
CREATE TABLE wishlist (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  product_id INT NOT NULL,
  added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (product_id) REFERENCES products(product_id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- ORDERS
CREATE TABLE orders (
  order_id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  items JSON NOT NULL, -- [{"product_id":1,"qty":2}, ...]
  total DECIMAL(10,2) NOT NULL,
  status ENUM('pending','processing','shipped','completed','cancelled') DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- SUPPORT TICKETS
CREATE TABLE support_tickets (
  ticket_id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NULL,
  subject VARCHAR(255),
  message TEXT,
  status ENUM('open','in_progress','closed') DEFAULT 'open',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- CONTACT MESSAGES (public contact form)
CREATE TABLE contact_messages (
  msg_id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120),
  email VARCHAR(150),
  message TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- SAMPLE DATA: Users
-- Note: password_hash left NULL for sample user. Use provided PHP register or run an UPDATE with a password_hash generated by PHP's password_hash().
INSERT INTO users (name, email, role, created_at) VALUES
('Sample User','user1@techverse.local','user', NOW()),
('Demo Admin','admin@techverse.local','admin', NOW());

-- SAMPLE DATA: Products (Phones, Laptops, Tablets, Smartwatches, Earbuds, PCs)
INSERT INTO products (sku, name, category, brand, price, image_url, short_desc, description, rating, stock) VALUES
('TV-0001','NovaPhone X1 - 6.5\" OLED, 128GB','Phones','NovaTech',699.00,'/img/novaphone_x1.jpg','6.5\" OLED, 128GB, 48MP camera','NovaPhone X1 full description...',4.5,25),
('AP-0102','Aeris Pro Laptop 14\" i7, 16GB RAM','Laptops','Aeris',1199.00,'/img/aeris_pro_14.jpg','14\" FHD, Intel i7, 16GB RAM','Aeris Pro full description...',4.6,12),
('SMP-2003','Tabster 11 - 11\" Tablet, 64GB','Tablets','Tabster',329.00,'/img/tabster11.jpg','11\" IPS, 64GB, Stylus support','Tabster 11 full description...',4.1,40),
('WCH-3004','PulseWatch S - Smartwatch','Wearables','PulseTech',199.00,'/img/pulsewatch_s.jpg','Heart-rate, GPS, 7-day battery','PulseWatch S full description...',4.0,30),
('EAR-4005','TrueBeats Lite - Wireless Earbuds','Audio','TrueBeats',79.00,'/img/truebeats_lite.jpg','Noise reduction, 24h case battery','TrueBeats Lite full description...',4.2,100),
('PC-5006','AssemblePro Desktop - Ryzen 5, 16GB','PCs','BuildIt',899.00,'/img/assemblepro_r5.jpg','Desktop build, fast SSD, GPU ready','AssemblePro full description...',4.3,8),
('TV-0007','NovaPhone Mini - 5.8\" Compact','Phones','NovaTech',499.00,'/img/novaphone_mini.jpg','Compact 5.8\", 64GB storage','NovaPhone Mini full description...',4.0,15),
('LP-0110','Aeris Air - Ultralight 13\"','Laptops','Aeris',899.00,'/img/aeris_air_13.jpg','13\" Ultralight, 8GB RAM','Aeris Air full description...',4.2,20);

-- Example: product categories can be derived from products.category
-- SAMPLE CART: (empty by default) - we'll add a cart item for Sample User
INSERT INTO cart_items (user_id, product_id, quantity, added_at) VALUES
(1, 1, 1, NOW());

-- SAMPLE WISHLIST
INSERT INTO wishlist (user_id, product_id, added_at) VALUES
(1, 2, NOW()),
(1, 5, NOW());

-- SAMPLE ORDER (for demo): items JSON contains objects with product_id and qty
INSERT INTO orders (user_id, items, total, status, created_at) VALUES
(1, '[{\"product_id\":1,\"qty\":1},{\"product_id\":5,\"qty\":2}]', (699.00 + 79.00*2), 'pending', NOW());

-- SAMPLE SUPPORT TICKET
INSERT INTO support_tickets (user_id, subject, message, status, created_at) VALUES
(1, 'Query about NovaPhone X1', 'Is NovaPhone X1 compatible with local GSM bands?', 'open', NOW());

-- SAMPLE CONTACT MESSAGE
INSERT INTO contact_messages (name, email, message, created_at) VALUES
('Visitor','visitor@example.com','Love the marketplace! When will you add more devices?', NOW());

-- Useful views (optional)
DROP VIEW IF EXISTS v_products_brand_price;
CREATE VIEW v_products_brand_price AS
SELECT product_id, sku, name, brand, category, price, rating, stock FROM products;

-- End of dump
